config/routes.rb
Rails.application.routes.draw do

  # omniauth route
  get "/auth/:provider/callback" =>  "sessions#create", as: 'create'

  get "logout" => "sessions#destroy", as: "logout"

  root to: 'pages#index'

  resources :products, except: [:destroy] do
    resources :reviews
  end

  resources :users, :categories, :orders, :addresses, :order_products

  get 'addresses/new/:redirect_to' => 'addresses#new', as: 'address_new'

  get 'cart' => 'pages#cart', as: 'cart'

  get 'account' => 'users#show', as: 'account'

  get 'account/edit' => 'users#edit', as: 'account_edit'

  put 'account/update' => 'users#update', as: 'account_update'

  patch 'toggle/:id' => 'users#switch_active', as: 'toggle'

  patch 'toggle_product/:id' => 'products#switch_active', as: 'toggle_product'

  get 'users/orders/:id' => 'orders#all', as: 'user_orders'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :uid, :provider, presence: true
  validates_uniqueness_of :email

  has_many :orders
  has_many :reviews
  has_many :addresses

  def self.build_from_github(auth_hash)
    user = User.new
    user.uid = auth_hash[:uid]
    user.provider = 'github'

    name = User.split_name(auth_hash['info']['name'])
    user.first_name = name.first
    user.last_name  = name.last

    user.email = auth_hash['info']['email']

    user.admin = false
    user.active = true

    return user
  end

  def self.split_name(name)
    unless name == nil
      array = name.split(' ')
      last_name = array.pop
      array.length == 0 ? first_name = "there" : first_name = array.join(' ')
      return first_name, last_name
    else
      return "there", "last name"
    end
  end

  def toggle_active
    # toggles active between true and false
    self.active = !self.active
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user
  before_action :check_active
  before_action :check_admin, only: [:new, :create, :index]
  before_action :find_uiq, only: [:edit, :create, :update, :destroy]

  def index ; end

  def show
    @addresses = Address.where(user_id: @user.id)
  end

  def new
    @user = User.new
  end

  def create
    # this should never happen since we are only creating users from github?
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User successfully added."
      redirect_to users_path
    else
      flash[:notice] = "User not created."
      rendirect_to users_path
    end
  end

  def edit ;  end

  def update
    if @user_in_question.update(user_params)
      flash[:notice] = "Information updated successfully."
      if @user != @user_in_question
        redirect_to users_path
      else
        redirect_to account_path
      end
    else
      flash[:notice] = "Your information could not be saved. Please check and try again"
      redirect_to account_edit_path
    end
  end

  def destroy
    @user_in_question.active = false
    @user_in_question.save
    redirect_to users_path
  end

  def switch_active
    user = User.find_by(id: params[:id])
    user.toggle_active
    user.save
    redirect_to users_path
  end

  private
  def find_user
    @user = User.find_by(id: session[:user_id])
    if !@user.nil?
      @order = Order.find_by(user_id: @user.id, order_status: 'cart')
      if @order.nil?
        @order = Order.create(user_id: @user.id, order_status: 'cart')
      end
    else
      @order = Order.create(order_status: 'cart')
    end
    return @user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :birthdate, :phone, :admin, :active, :uid, :provider)
  end

  def check_admin
    if @user.admin
      @users = User.all
    else
      flash[:notice] = "You do not have access to the requested page. Instead, here's your account page."
      redirect_to account_path
    end
  end

  def check_active
    if !@user.active
      flash[:notice] = "Your account is not active. Please contact support to be activated."
      redirect_to root_path
    end
  end

  def logged_in?
    if @user.id.nil?
      return false
    else
      return true
    end
  end

  # when the current user is an admin, find the user's profile that the admin would like to interact with
  def find_uiq
    if params[:id]
      @user_in_question = User.find_by(id: params[:id])
    else
      @user_in_question = @user
    end
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<%= form_for @user_in_question, method: method, path: path do |f| %>

<ul>
  <li><%= f.label :first_name %></li>
  <li><%= f.text_field :first_name %></li>

  <li><%= f.label :last_name %></li>
  <li><%= f.text_field :last_name %></li>

  <li><%= f.label :email %></li>
  <li><%= f.text_field :email %></li>

  <li><%= f.label :phone_number %></li>
  <li><%= f.text_field :phone %></li>

<% if @user.admin %>
  <li><%= f.label :active? %></li>
  <li><%= f.check_box :active %></li>

  <li><%= f.label :admin? %></li>
  <li><%= f.check_box :admin %></li>
<% end %>

  <li><%= f.submit class:"hollow button" %> </li>
</ul>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="format-forms">
<h1> Edit Account Information </h1>
  <p class="flash-notice"><%= render partial: 'shared/flash_notice' %></p>
  <%= render partial: 'user_form', locals: {path: 'users_path', method: :put} %>
</div>

app/views/users/index.html.erb
<div class="row">

  <h1 class="center-text">All Users</h1>
  <div class="mid-page-space"></div>


    <table class="style-user-table">
      <tr>
        <th>Name</th>
        <th>ID</th>
        <th>Edit User</th>
        <th>Change Status</th>
        <th>Delete User</th>
        <th>See Orders</th>
      </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%="#{user.first_name} #{user.last_name}" %></td>
        <td><%="#{user.id}" %></td>
        <td><%= link_to("Edit", edit_user_path(user.id)) %></td>
        <td><%= link_to("Make #{active_for_button(user)}", toggle_path(user.id), method: :patch) %></td>
        <td><%= link_to("Delete", user_path(user.id), method: :delete, data: {confirm: "Are you sure? Deleting a user is permanent."}) %></td>

        <td><%= link_to("See orders", user_orders_path(user.id)) %></td>
      </tr>
    <% end %>
    </table>

  </div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1 class="center-text"><%= "Welcome, #{@user.first_name}" %></h1>
<div class="mid-page-space"></div>
<h4 class="alert center-text"><%= render partial: 'shared/flash_notice' %></h4>

<div class="row">
  <section class="small-4 columns">
    <h3>Account Info</h3>
    <p><strong><%= "Name: #{@user.first_name} #{@user.last_name}" %></strong></p>
    <p><%= "Email: #{@user.email}" %></p>
    <p><%= "Phone: #{@user.phone}" %></p>

    <div class="mid-page-space"></div>

    <ul>
      <li><%= button_to 'Edit Account', account_edit_path, class:"hollow button", method: :get%></li>
      <li><%= button_to 'Your Orders', user_orders_path(@user.id), class:"hollow button", method: :get%></li>
    </ul>


  </section>

  <section class="small-8 columns">
    <h3>Addresses</h3>

    <div class="row">
      <% @addresses.each do |address|%>
        <div class="small-6 columns">
          <p><strong><%= address.kind %></strong></p>
          <p><%= address.first_name %>
          <%= address.last_name %></p>
          <p><%= address.street1 %></p>
          <p><%= address.street2 %></p>
          <p><%= address.city %>,
          <%= address.state %>
          <%= address.zip %>
          <%= address.country %></p>
          <p><%= address.phone %></p>
          <%= button_to "Edit", edit_address_path(address.id), class:"hollow button" %>
          <%= button_to "Delete", address_path(address.id), method: :delete, class:"hollow button" %>

        </div>
      <% end %>

      <div class="small-12 columns"><%= button_to 'Add a New Address', address_new_path("1"), :method => :get, class:"hollow button"%></div>


  </section>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>