config/routes.rb
Rails.application.routes.draw do

  # omniauth route
  get "/auth/:provider/callback" =>  "sessions#create", as: 'create'

  get "logout" => "sessions#destroy", as: "logout"

  root to: 'pages#index'

  resources :products, except: [:destroy] do
    resources :reviews
  end

  resources :users, :categories, :orders, :addresses, :order_products

  get 'addresses/new/:redirect_to' => 'addresses#new', as: 'address_new'

  get 'cart' => 'pages#cart', as: 'cart'

  get 'account' => 'users#show', as: 'account'

  get 'account/edit' => 'users#edit', as: 'account_edit'

  put 'account/update' => 'users#update', as: 'account_update'

  patch 'toggle/:id' => 'users#switch_active', as: 'toggle'

  patch 'toggle_product/:id' => 'products#switch_active', as: 'toggle_product'

  get 'users/orders/:id' => 'orders#all', as: 'user_orders'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: :true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, except: [:index, :new, :create]
  before_action :find_user

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category created successfully!"
      redirect_to :action => "index"
    else
      flash[:notice] = "Please be sure you have completed all fields."
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category successfully saved!"
      redirect_to :action => "index"
    else
      flash[:notice] = "Please be sure you have completed all fields."
      render :action => :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to root_path
  end




  private
  def find_category
    @category = Category.find(params[:id])
    if @category.nil?
      render :file => 'public/404.html', :status => :not_found
    end
  end

  def category_params
    params.require(:category).permit(:name,:picture)
  end

  def find_user
    @user = User.find_by(id: session[:user_id])
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categoryform.html.erb
<%= form_for @category,
  url: action_name do |f| %>
<ul>
  <li><%= f.label :name %></li>
  <li><%= f.text_field :name %></li>

  <!-- will need to add gem and figure out how to upload photos -->
  <li><%= f.file_field :picture%></li>

  <li><%= f.submit class:"hollow button"%> </li>
</ul>

<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<div class="format-forms">
  <h1>Edit a Category</h1>
  <p class="flash-notice"><%= render partial: 'shared/flash_notice' %></p>
  <%= render partial: "categoryform", method: :post, locals: { action_name: category_path, params: {id: @category.id }} %>
</div>

app/views/categories/index.html.erb
<h1 class="center-text">Shop Products by Category</h1>
<p class="flash-notice"><%= render partial: 'shared/flash_notice' %></p>
<div class="row small-up-1 medium-up-2">
  <% @categories.each do |category| %>
  <article class="column center-text">
      <%=link_to image_tag(category.picture, :alt => category.name, :title => category.name), category_path(category.id) %>
      <h3><%= link_to category.name, category_path(category.id) %></h3>

  </article>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="format-forms">
  <h1>Add a Category</h1>
  <p class="flash-notice"><%= render partial: 'shared/flash_notice' %></p>
  <%= render partial: "categoryform", locals: { action_name: categories_path } %>
</div>

app/views/categories/show.html.erb
<h1 class="center-text">Shop <%= @category.name %></h1>

<div class="row small-up-1 medium-up-2 large-up-3">
  <% Product.where(category_id: @category.id).each do |product| %>
  <article class="column">
    <%=link_to((image_tag(product.picture, :alt => product.name, :title => product.name)), product_path(product.id))%>
    <h3><%= link_to product.name, product_path(product.id) %></h3>
    <%= image_tag "#{product.average_rating}lemon.jpg" %>
    <h4><%= number_to_currency((product.price/100.0)) %></h4>
  </article>
  <% end %>
</div>

app/views/categories/udpate.html.erb
<h1>Categories#udpate</h1>
<p>Find me in app/views/categories/udpate.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#udpate</h1>
<p>Find me in app/views/categories/udpate.html.erb</p>