config/routes.rb
Rails.application.routes.draw do

  # omniauth route
  get "/auth/:provider/callback" =>  "sessions#create", as: 'create'

  get "logout" => "sessions#destroy", as: "logout"

  root to: 'pages#index'

  resources :products, except: [:destroy] do
    resources :reviews
  end

  resources :users, :categories, :orders, :addresses, :order_products

  get 'addresses/new/:redirect_to' => 'addresses#new', as: 'address_new'

  get 'cart' => 'pages#cart', as: 'cart'

  get 'account' => 'users#show', as: 'account'

  get 'account/edit' => 'users#edit', as: 'account_edit'

  put 'account/update' => 'users#update', as: 'account_update'

  patch 'toggle/:id' => 'users#switch_active', as: 'toggle'

  patch 'toggle_product/:id' => 'products#switch_active', as: 'toggle_product'

  get 'users/orders/:id' => 'orders#all', as: 'user_orders'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  # has_and_belongs_to_many :orders
  has_many :reviews

  # order_products association
  has_many :order_products
  has_many :orders, through: :order_products

  # product must have a name
  validates :name, presence: true

  # product must mave a price, that price must be an integer, and the price must be larger than zero
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # product must either be active or inactive
  # validates :active, inclusion: { in: [true, false] }
  # validates :active, exclusion: { in: [nil] }

  # product must be associated with a category. don't put this in the category validations or else we'll get an infinite loop!
  validates :category_id, presence: true
  validates_associated :category

  # search bar
  def self.search(search)
    where('description LIKE ? OR name LIKE ?', "%#{search}%", "%#{search}%")
  end

  # archive method changes active to false
  def archive
    update_attribute(:active, false)
  end

  def toggle_active
    # toggles active between true and false
    self.active = !self.active
  end

  def average_rating
    if self.reviews.length != 0
      count = self.reviews.length
      total = 0

      self.reviews.each do |review|
        total += review.rating
      end

      return total / count
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_user
  before_action :find_product, except: [:index, :new, :create]


  def index
    @products = Product.all.where(active: true)

    if params[:search]
      @products = Product.search(params[:search]).order("name DESC")
    else
      @products = Product.all.order('name DESC')
    end
  end
  # why is review in products controller, do we have a review controller?
  def show
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    if @product.save
      flash[:notice] = "Product created successfully!"
      redirect_to action: "index"
    else
      flash[:notice] = "Please be sure you have completed all fields."
      render :action => :new
    end
  end

  def edit
    # @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def update
    @product.category_id = params[:category_id]
    if @product.update(product_params)
      flash[:notice] = "Product successfully saved!"
      redirect_to action: "show"
    else
      flash[:notice] = "Please be sure you have completed all fields."
      render :action => :edit
    end
  end
  #
  # def destroy
  #   @product.destroy
  #   redirect_to root_path
  # end

  def switch_active
    product = Product.find_by(id: params[:id])
    product.toggle_active
    product.save
    redirect_to product_path
  end

  private
  def find_user
    @user = User.find_by(id: session[:user_id])
    if !@user.nil?
      @order = Order.find_by(user_id: @user.id, order_status: 'cart')
      if @order.nil?
        @order = Order.create(user_id: @user.id, order_status: 'cart')
      end
    else
      # This should really be sessions
      @order = Order.create(order_status: 'cart')
    end
  end

  def find_product
    @product = Product.find(params[:id])
    if @product.nil?
      render :file => 'public/404.html', :status => :not_found
    end
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :inventory_qty, :category_id, :picture)
  end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_productform.html.erb
<%= form_for @product,
  url: action_name do |f| %>
<ul>
  <li><%= f.label :name %></li>
  <li><%= f.text_field :name %></li>

  <li><%= f.label :description %></li>
  <li><%= f.text_area :description %></li>

  <li><%= f.label :price %></li>
  <li><%= f.text_field :price %></li>

  <li><%= f.label "Quantity on Hand" %></li>
  <li><%= f.text_field :inventory_qty%></li>
<!-- move Category.all to controller once we get form working - right now I have it here for debugging purposes. For edit dropdown would be great if it prefilled with current category  -->
  <li><%= f.label :category_id %></li>
  <li><%= select_tag(:category_id, options_for_select(Category.all.map{|c| [ c.name, c.id ] }, @product.category_id), :prompt => "Select one!") %></li>

  <li><%= f.label "Active Status" %></li>
  <li><%= f.select :active, [['Active', true], ['Inactive', false]] %></li>

  <li><%= f.file_field :picture%></li>
  <li><%= f.submit class:"hollow button" %> </li>

</ul>

<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<div class="format-forms">
  <h1>Edit <%= @product.name %></h1>
  <p class="flash-notice"><%= render partial: 'shared/flash_notice' %></p>
  <%= render partial: "productform", method: :post, locals: { action_name: product_path, params: {id: @product.id }} %>
</div>

<div class="end-page-space"></div>

app/views/products/index.html.erb
<h1 class="center-text">Shop All Products</h1>
<h4 class="alert center-text"><%= render partial: 'shared/flash_notice' %></h4>

<div class="row small-up-1 medium-up-2 large-up-3">
  <% @products.each do |product| %>
  <article class="column">
    <% if product.active %>
      <%=link_to image_tag(product.picture, :alt => "product photo", :title => product.name), product_path(product.id) %>
      <h3><%= link_to product.name, product_path(product.id) %></h3>
      <%= image_tag "#{product.average_rating}lemon.jpg" %>
      <h4><%= number_to_currency((product.price/100.0)) %></h4>

    <% end %>
  </article>
  <% end %>
</div>


<% if !@user.nil? %>
  <% if @user.admin %>
  <h1 class="center-text">INACTIVE PRODUCTS</h1>
  <div class="row small-up-1 medium-up-2 large-up-3">
    <% @products.each do |product| %>
    <article class="column">
      <% if !product.active %>
        <%=link_to image_tag(product.picture, :alt => "product photo", :title => product.name), product_path(product.id) %>
        <p class="center-text"><%= link_to product.name, product_path(product.id) %></p>
      <% end %>
      </article>
    <% end %>
  <% end %>
<% end %>
</div>

<!-- if search form in nav bar returns nothing -->
<section>
  <% if @products.blank? %>
    <h4>There are no products containing the search term <em><%= params[:search] %></em>.</h4>
  <% end %>
</section>

app/views/products/new.html.erb
<div class="format-forms">
  <h1>Add a Product</h1>
  <p class="flash-notice"><%= render partial: 'shared/flash_notice' %></p>
  <%= render partial: "productform", locals: { action_name: products_path } %>
</div>

app/views/products/show.html.erb
<div class="row">
  <section class="small-4 columns">
    <ul>
      <li class="showprod"><%=image_tag(@product.picture, :alt => "product photo", :title => @product.name)%></li>
    </ul>
  </section>
  <section class="small-8 columns">
    <ul class="line-height">
      <li class="admin-button">
        <h2>
          <%= @product.name %>
        </h2>
          <% if !@user.nil? %>
            <% if @user.admin %>
                <%= button_to 'Edit', edit_product_path(params[:id]), class:"hollow button", method: :get %>
                <%= button_to("Mark #{active_for_button(@product)}", toggle_product_path(@product.id), class:"hollow button", method: :patch, data: {confirm: 'Are you sure you want to make this product inactive?'}) %>
            <% end  %>
          <% end  %>
      </li>

      <li>
        <h5>
          <%=@product.description%>
        </h5>
      </li>
      <li><h4><%= number_to_currency((@product.price/100.0))%></h4></li>

      <% if @product.inventory_qty <= 0 %>
        <li><h4 class=alert>OUT OF STOCK</h4></li>
      <% elsif @user.nil? %>
        <li><h4 class='hollow button'><a href='/auth/github'>Login to Add to Cart</a></h4></li>
      <% else %>
        <li><h6><%= @product.inventory_qty %> in stock</h6></li>
        <%= form_for :order_products, url: order_products_path do |f| %>
          <%= f.hidden_field :id, value: @product.id %>
          <%= f.label :delta, "Quantity" %>
          <%= f.number_field :delta, value: 1%>
          <%= f.submit "Add to Cart", class:"hollow button" %>
        <% end %>
      <% end %>


    </ul>
  </section>
</div>

<div class="row reviews-show">
  <section class="small-6 columns">
    <ul class="line-height">
      <li><h3> Product Reviews </h3></li>
      <% if @product.reviews.empty? %>
        <%= "No reviews yet." %>
      <% else %>
      <% @product.reviews.each do |review| %>
          <p><strong><%= review.subject %></strong></p>
          <p>Reviewer: <%= review.user.first_name %></p>
          <p><%= show_lemons(review) %></p>
          <p><%= review.body %></p>
        </br>
        <% end %>
      <% end %>
    </ul>
  </section>



  <section class="small-6 columns">
    <% if session[:user_id] != nil %>
    <ul>
      <li><h3>Leave a review for <%= @product.name %></h3></li>
    </ul>
      <%= render partial: "reviews/reviewform", locals: {  action_name: product_reviews_path(@product.id)} %>
    <% end %>
  </section>
</div>
<div class="end-page-space"></div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>